### ISSUE TITLE
Support Firefox 

### ISSUE THREAD

**Issue by mtfum** [funzin/ImgConverter#27]
I would like to use in Firefox add-on.
Do you have any plans for that?
Thank you for the great extension!

**Comment by funzin** [comment]
@mtfum 
I'm a Chrome user, so I wasn't thinking about firefox.😅
But it looks like an easy transition, so I'll try to work on it this weekend.

**Comment by funzin** [comment]
@mtfum 
https://addons.mozilla.org/en-US/firefox/addon/imgconverter/
ImgConverter is now supported on firefox, so give it a try!
