### ISSUE TITLE
Uncaught SyntaxError: Identifier 'MarkdownImage' has already been declared

### ISSUE THREAD

**Issue by baolongnt** [funzin/ImgConverter#36]
I get the following error when hitting extension button
`Uncaught SyntaxError: Identifier 'MarkdownImage' has already been declared`

Note: We are on a private instance of GitHub. The extension works on GitHub public instance.

**Comment by funzin** [comment]
@baolongnt 
Thank you for your reply!

I would like to check syntaxError
Can you tell me about details?

>private instance of GitHub
Is it like GitLab?

I haven't develop like your environment and I would like to verify if it happens in a similar environment

**Comment by baolongnt** [comment]
The private instance of GitHub is a version of Github that is only accessible to people within our company. The code may be a few months behind the public version of Github.

I looked into it a bit more and noticed 2 things
1. The error message happens regardless of the GitHub version. It happens when you hit the extension's button more than once
2. Our Github instance does not preserve the file name extension (ex: png, gif or jpg) in the URL it generates. Hence, the regex that parses the text fails. 
--> Can we change the code so that it catches URLs with no image file extension?
Ex: https://xxx.github.com/user/xxx/files/xxxx-xxxx-xxxx-xxxx-xxxx

**Comment by funzin** [comment]
> Our Github instance does not preserve the file name extension (ex: png, gif or jpg) in the URL it generates. Hence, the regex that parses the text fails.

ImgConverter couldn't convert if image file don't have name extension
Because it's just executing a regular expression

**Comment by baolongnt** [comment]
Why does the regular expression need to look at the file extension?

Per the GitHub documentation, [Mastering Markdown](https://guides.github.com/features/mastering-markdown/), 
* Images are use the `![Alt Text](url)` format
* Links use `[Label](url)`

So we can differentiate them via the `!` at the beginning and there should not  be a need for having `(jpg|jpeg|png|gif)` in the regular expression.

**Comment by funzin** [comment]
I understand about what you said.
Certainly, ImgConverter don't need to check file extension.
I will fix it as soon as

**Comment by baolongnt** [comment]
Thanks for the fix. When will the change make it to the Chrome app store?

**Comment by funzin** [comment]
I submited new version yesterday.
If the app is published, I will tell you.

**Comment by funzin** [comment]
@baolongnt 
ImgConverter v2.0.0 is published to Chrome app store
You can confirm it

**Comment by baolongnt** [comment]
It works great. Thank you!
