### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Hanalm666** [funzin/ImgConverter#51]
ImgConverter does Not work in http://xxxx.img ?

**Comment by funzin** [comment]
@Hanalm666 
Hi, Hanalm!

Maybe, it will work event if extension is `img`.

Could you attach text that you want to convert?

**Comment by funzin** [comment]
@Hanalm666 

Thanks, I understand.

ImgConverter supports dropped picture in text area. (like `![image-url]`)
So it doesn't support primitive image url text.

**Comment by Hanalm666** [comment]
Owh..when I change the http:// to https:// in the url it works fine.

**Comment by funzin** [comment]
I'm so glad.
Github creates https prefix image url, so I support https link only.
https://github.com/funzin/ImgConverter/blob/master/src/js/convert-to-img-tag.js#L63
